version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.7.2

    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test
